Fix after merge

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,24 +5,33 @@
 variables:
  GIT_DEPTH: 5
  GIT_OPTIONS: "--allow-unrelated-histories"
- # GLOBAL
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  MAVEN_CLI_OPTS: "--batch-mode --show-version "
- BUILD_PATH: "opensilex-release/target"
+ BUILD_PATH: "$CI_PROJECT_DIR/opensilex-release/target"
  # DEFAULT SERVER MAVEN VERSION
  MVN_VERSION: 3.6.3
  # DEFAULT SERVER JAVA VERSION
  JAVA_VERSION: 11
+ RSYNC_INSTANCES_OPTIONS: "--progress --delete"
+ RSYNC_INSTANCES_PATH: "/home/phis/opensilex-instances/bin"
+ RSYNC_INSTANCES_DATA: "/home/phis/opensilex-instances/data"
+ RSYNC_INSTANCES_LOGS: "/home/phis/opensilex-instances/logs"
+ RSYNC_INSTANCES_LOGS_ARCHIVED: "/home/phis/opensilex-instances/logs/old"
  REVISION: 'INSTANCE-SNAPSHOT'
+ DEV_TOOLS_CONFIGURATION_FILES_PATH: "instances-configuration"
+ STOP_SERVER_OPTS: "--adminPort=$ADMIN_PORT --host=$REMOTE_SERVER_IP --CONFIG_FILE=$INSTANCE_CONFIGURATION_FILE_NAME"
+ START_SERVER_OPTS: "--adminPort=$ADMIN_PORT --host=$REMOTE_SERVER_IP --port=$PORT --CONFIG_FILE=$INSTANCE_CONFIGURATION_FILE_NAME --DEBUG -d"
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_CACHE_FOLDER: "$CI_PROJECT_DIR/.m2/repository"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache_yarn"
- NODE_CACHE: "$CI_PROJECT_DIR/.node"
+ NODE_CACHE: "$CI_PROJECT_DIR/opensilex-dev/.node"
  EMBDED_MONGO_CACHE: "/root/.embedmongo/"
- 
+ GITLAB_HTTPS: "false"
+
+
 ########################
 ##  CACHE TEMPLATE
 ########################
@@ -38,6 +47,7 @@ variables:
       - $NODE_CACHE
       - $EMBDED_MONGO_CACHE
 
+
 ########################
 ##  BUILD TEMPLATE
 ########################
@@ -45,10 +55,6 @@ variables:
 .build:instance: &build_template_with_opensilex
   <<: *cache_dependencies
   before_script: 
-    - |
-      if [ ! -z "$COMMIT_SHA_OPENSILEX_DEV" ]; then
-        git checkout $COMMIT_SHA_OPENSILEX_DEV
-      fi
     - rm -r $CI_PROJECT_DIR/phis-ws
     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@forgemia.inra.fr/OpenSILEX/phis-ws.git --branch modularity
     - |
@@ -63,222 +69,124 @@ variables:
     - schedules
   artifacts:
     expire_in: "3 week"
-    
-# ########################
-# ##  DEFAULT BUILD CACHE 
-# ########################
 
-opensilex:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - master
-    
-# Trigger pipeline for sixtine module deployment
-trigger:sixtine:build:
+########################
+##  DEPLOY SSH CONFIGURATION TEMPLATE
+########################
+.deploy_opensilex_before_script: &deploy_opensilex_before_script
+  before_script:
+    # test variables before deployement
+    -  if [ -z "$RSYNC_USER" ]; then echo "Missing RSYNC_USER variable"; exit 1; fi
+    -  if [ -z "$REMOTE_SERVER_IP" ]; then echo "Missing REMOTE_SERVER_IP variable"; exit 1; fi
+    -  if [ -z "$CONFIGURATION_FILES_PATH" ]; then echo "Missing CONFIGURATION_FILES_PATH variable"; exit 1; fi
+    -  if [ -z "$INSTANCE_CONFIGURATION_FILE_NAME" ]; then echo "Missing INSTANCE_CONFIGURATION_FILE_NAME variable"; exit 1; fi
+    -  if [ -z "$SSH_KEY" ]; then echo "Missing SSH_KEY variable"; exit 1; fi
+    -  if [ -z "$ADMIN_PORT" ]; then echo "Missing ADMIN_PORT variable"; exit 1; fi
+    -  if [ -z "$PORT" ]; then echo "Missing PORT variable"; exit 1; fi
+    ##
+    ## Create the SSH directory and give it the right permissions
+    ##
+    - mkdir -p ${HOME}/.ssh
+    - chmod 700 ${HOME}/.ssh
+    ##
+    ## Install ssh-agent if not already installed, it is required by Docker.
+    ## (change apt-get to yum if you use an RPM-based image)
+    ##
+    - 'which ssh-agent || ( apt-get update && apt-get install openssh-client -y )'
+    ##
+    ## Run ssh-agent (inside the build environment)
+    ##
+    - eval $(ssh-agent -s)
+    ##
+    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
+    ## We're using tr to fix line endings which makes ed25519 keys work
+    ## without extra base64 encoding.
+    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
+    ##
+    - mkdir -p ${HOME}/.ssh && touch ${HOME}/.ssh/known_hosts
+    - ssh-keyscan -H "$REMOTE_SERVER_IP" >> ${HOME}/.ssh/known_hosts
+    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ${HOME}/.ssh/config
+    - echo "$SSH_KEY" >> ${HOME}/.ssh/id_rsa
+    - chmod 600 ${HOME}/.ssh/id_rsa
+
+########################
+##  DEPLOY OPENSILEX TEST TEMPLATE
+########################
+
+.deploy:opensilex:instance: &deploy_opensilex_template
   stage: deploy
-  image: curlimages/curl
+  when: manual
+  image: instrumentisto/rsync-ssh
+  environment:
+    url: http://$REMOTE_SERVER_IP:$PORT
   script:
-    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$CI_COMMIT_SHA" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/1757/trigger/pipeline
-  only:
-    - master    
-  needs: 
-    - job: "opensilex:build"
-
-      
-trigger:phis:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=phis-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - master    
-  needs: 
-    - job: "opensilex:build"
-
-
-# ##########################################
-# ##  BUILD & DEPLOY FOR MISTEA TEAM
-# ##########################################
-
-# #########
-# Alice
-# #########
-
-alice:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - alice
-
-trigger:alice:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=alice-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - alice    
-  needs: 
-    - job: "alice:build"    
+    - apk add curl git
+    - rm -R $CI_PROJECT_DIR/opensilex-dev-tools
+    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@forgemia.inra.fr/OpenSILEX/opensilex-dev-tools.git --branch master $CI_PROJECT_DIR/opensilex-dev-tools
+    - ls $CI_PROJECT_DIR/opensilex-dev-tools
+    # Create directories
+    - ls $CI_PROJECT_DIR/$REVISION
+    - echo "Create directory ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}"
+    - echo "Create directory ${RSYNC_INSTANCES_DATA}/${RSYNC_DIR}"
+    - echo "Create directory ${RSYNC_INSTANCES_LOGS}"
+    - echo "Create directory ${RSYNC_INSTANCES_LOGS_ARCHIVED}"
+    - ssh -i ${HOME}/.ssh/id_rsa -p22 $RSYNC_USER@$REMOTE_SERVER_IP "mkdir -p $RSYNC_INSTANCES_PATH/$RSYNC_DIR; mkdir -p $RSYNC_INSTANCES_LOGS; mkdir -p $RSYNC_INSTANCES_LOGS_ARCHIVED; mkdir -p $RSYNC_INSTANCES_DATA/$RSYNC_DIR;"
+    - echo "Upload files"
+    - rsync -arzv -e "ssh  -i ${HOME}/.ssh/id_rsa" $RSYNC_INSTANCES_OPTIONS  $CI_PROJECT_DIR/$REVISION/* $RSYNC_USER@$REMOTE_SERVER_IP:$RSYNC_INSTANCES_PATH/$RSYNC_DIR
+    - echo "ls ${CONFIGURATION_FILES_PATH}"
+    - ls $CI_PROJECT_DIR/opensilex-dev-tools/$CONFIGURATION_FILES_PATH
+    - echo "scp -i ${HOME}/.ssh/id_rsa -o 'StrictHostKeyChecking no' $CI_PROJECT_DIR/opensilex-dev-tools/$CONFIGURATION_FILES_PATH/* ${RSYNC_USER}@${REMOTE_SERVER_IP}:${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}"
+    - scp -i ${HOME}/.ssh/id_rsa -o "StrictHostKeyChecking no" $CI_PROJECT_DIR/opensilex-dev-tools/$CONFIGURATION_FILES_PATH/* $RSYNC_USER@$REMOTE_SERVER_IP:$RSYNC_INSTANCES_PATH/$RSYNC_DIR
+    - echo "Remove dependencies list cache"
+    - ssh -i ${HOME}/.ssh/id_rsa -p22 $RSYNC_USER@$REMOTE_SERVER_IP "rm -f ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}/.opensilex.dependencies"
+    - echo "Check files"
+    - ssh -i ${HOME}/.ssh/id_rsa -p22 $RSYNC_USER@$REMOTE_SERVER_IP "ls ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR};"
+    - echo "Restarting server with options ${START_SERVER_OPTS}"
+    - ssh -i ${HOME}/.ssh/id_rsa -p22 $RSYNC_USER@$REMOTE_SERVER_IP "cd ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}; java -jar ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}/opensilex.jar server stop $STOP_SERVER_OPTS"
+    - ssh -i ${HOME}/.ssh/id_rsa -p22 $RSYNC_USER@$REMOTE_SERVER_IP "cd ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}; java -jar ${RSYNC_INSTANCES_PATH}/${RSYNC_DIR}/opensilex.jar server start $START_SERVER_OPTS"
+  except:
+    - schedules    
     
 # #########
-# Anne
-# #########
-
-anne:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - anne
-    
-trigger:anne:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=anne-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - anne    
-  needs: 
-    - job: "anne:build"    
-    
-    
-# #########
-# Arnaud
-# #########
-
-arnaud:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - arnaud
-    
-trigger:arnaud:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=arnaud-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - arnaud
-  needs: 
-    - job: "arnaud:build"
-    
-# #########
-# Julien
-# #########
-    
-julien:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - julien
-    
-trigger:julien:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=julien-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - julien
-  needs: 
-    - job: "julien:build"       
-
-# #########
-# Renaud
-# #########
-
-renaud:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - renaud
-    
-trigger:renaud:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=renaud-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - renaud
-  needs: 
-    - job: "renaud:build"   
-    
-# #########
-# Vincent
+# VINCENT
 # #########
 
 vincent:build:
   <<: *build_template_with_opensilex
   script: 
     - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
+    - ls  $BUILD_PATH/
+    - ls  $BUILD_PATH/opensilex-release-$REVISION
+    - mv $BUILD_PATH/opensilex-release-$REVISION $CI_PROJECT_DIR/$REVISION
   artifacts:
     paths:
-      - $REVISION
+      - $CI_PROJECT_DIR/$REVISION
   only:
     - vincent
+    
+###################################
+##  VINCENT-TEST-SNAPSHOT-DEPLOYMENT
+###################################
 
-trigger:vincent:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=vincent-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
+test:vincent:deploy:
+  <<: *deploy_opensilex_before_script
+  <<: *deploy_opensilex_template
+  when: on_success  
+  variables:
+    RSYNC_USER: "phis"
+    REMOTE_SERVER_IP: "138.102.159.37"
+    RSYNC_DIR: "mistea/vincent"
+    CONFIGURATION_FILES_PATH: "${DEV_TOOLS_CONFIGURATION_FILES_PATH}/mistea/vincent"
+    INSTANCE_CONFIGURATION_FILE_NAME: "phis.test.yml"
+    SSH_KEY: "$TEST_SSH_PRIVATE_KEY"
+    ADMIN_PORT: 4086
+    PORT: 8086
+    PROJECT_ID: 403
+    BRANCH: vincent
   only:
     - vincent
-  needs: 
-    - job: "vincent:build"
-
-
-# #########
-# Ephesia
-# #########
-
-ephesia:build:
-  <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$REVISION
-    - mv $BUILD_PATH/opensilex-release-$REVISION $REVISION
-  artifacts:
-    paths:
-      - $REVISION
-  only:
-    - ephesia
-
-trigger:ephesia:deploy:test:
-  stage: deploy
-  image: curlimages/curl
-  script:
-    - curl --request POST --form "variables[DEPLOY]=ephesia-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
-  only:
-    - ephesia
-  needs: 
-    - job: "ephesia:build"    
+  environment:
+    name: vincent-test
+    url: http://138.102.159.37:8086
+  needs:
+    - vincent:build
