Try changes to opensilex commands in gitlab ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -824,21 +824,21 @@ test:gabriel:front-test:
         - dockerd &
         - docker compose -p test up &
         - cd $CI_PROJECT_DIR/artifacts/$OPENSILEX_APP_REVISION
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8081 --adminPort=4081 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8081 --adminPort=4081 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml
+        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8081 --adminPort=4081 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8081 --adminPort=4081 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
         - cd $CI_PROJECT_DIR/opensilex-front-tests/e2e
         - |
             # Check if OpenSILEX process has started on port 8081 three times, once every 15 seconds
             for attempt in {1..3}; do
                 sleep 15 # Wait for 15 seconds before the attempt
                 # Check if port 8081 is in use
-                if sudo ss -ltnp | grep ':8081 '; then
+                if ss -ltnp | grep ':8081 '; then
                     echo "Process started on port 8081."
                     break # Break the loop if port 8081 is in use
                 else
@@ -848,7 +848,7 @@ test:gabriel:front-test:
             
             # Check if port 8081 was never in use during the attempts
             if [[ $attempt -eq 3 ]]; then
-                echo "Error: OpenSILEX never started on port 8081 during the allowed 30 seconds." >&2
+                echo "Error: OpenSILEX never started on port 8081 during the allowed 45 seconds." >&2
                 # exit 1
             fi
             
