Added script to check for opensilex start

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -831,6 +831,26 @@ test:gabriel:front-test:
     - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8080 --DEBUG --CONFIG_FILE=/opensilex_mod.yml"
     - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8080 --DEBUG --CONFIG_FILE=/opensilex_mod.yml
     - cd $CI_PROJECT_DIR/opensilex-front-tests/e2e
+    - |
+      # Check if OpenSILEX process has started on port 8080 three times, once every 10 seconds
+      for attempt in {1..3}; do
+        # Check if port 8080 is in use
+        if sudo ss -ltnp | grep ':8080 '; then
+          echo "Process started on port 8080."
+          break # Break the loop if port 8080 is in use
+        else
+          echo "Port 8080 is not in use. Attempt $attempt of 3."
+          sleep 10 # Wait for 10 seconds before the next attempt
+        fi
+      done
+
+      # Check if port 8080 was never in use during the attempts
+      if [[ $attempt -eq 3 ]]; then
+        echo "Error: OpenSILEX never started on port 8080 during the allowed 30 seconds." >&2
+        exit 1
+      fi
+
+      echo "OpenSILEX has started on port 8080."
     - sleep 30 # Check port opened in a for or while
     - npm ci
     - PLAYWRIGHT_HTML_REPORT=$CI_PROJECT_DIR/artifacts/front-tests/playwright-report npx playwright test --output $CI_PROJECT_DIR/artifacts/front-tests/test-results  #  --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL    for sharding
