Release 1.0.0-rc+5

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -30,6 +30,7 @@ variables:
   MAVEN_CLI_OPTS: "--batch-mode --show-version -c"
   MAVEN_CACHE_FOLDER: "$CI_PROJECT_DIR/.m2/repository"
   MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
+  MAVEN_SKIP_TESTS: "false"
   # DEFAULT SERVER MAVEN VERSION
   MVN_VERSION: 3.6.3
   # DEFAULT SERVER JAVA VERSION
@@ -91,12 +92,14 @@ variables:
   stage: build
   image: maven:$MVN_VERSION-jdk-$JAVA_VERSION
   script:
-    - mvn clean install $MAVEN_CLI_OPTS -Drevision=$OPENSILEX_APP_REVISION
+    - mvn clean install $MAVEN_CLI_OPTS -Drevision=$OPENSILEX_APP_REVISION -DskipTests=$MAVEN_SKIP_TESTS
     - ls $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION
-    - mv $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION $OPENSILEX_APP_REVISION
+    - if [ -d "artifacts" ]; then rm -r artifacts; fi
+    - mkdir artifacts
+    - mv $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION artifacts/$OPENSILEX_APP_REVISION
   artifacts:
     paths:
-      - $OPENSILEX_APP_REVISION
+      - artifacts
     expire_in: "3 week"
 
 ########################
@@ -153,14 +156,14 @@ variables:
     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@forgemia.inra.fr/OpenSILEX/opensilex-dev-tools.git --branch master $CI_PROJECT_DIR/opensilex-dev-tools
     - ls $CI_PROJECT_DIR/opensilex-dev-tools
     # Directory details
-    - ls $CI_PROJECT_DIR/$OPENSILEX_APP_REVISION
+    - ls $CI_PROJECT_DIR/artifacts/$OPENSILEX_APP_REVISION
     - echo "Create directory ${RSYNC_INSTANCES_BIN_PATH}/${REMOTE_SERVER_RSYNC_DIR}"
     - echo "Create directory ${RSYNC_INSTANCES_DATA_PATH}/${REMOTE_SERVER_RSYNC_DIR}"
     - echo "Create directory ${RSYNC_INSTANCES_LOGS_PATH}"
     - echo "Create directory ${RSYNC_INSTANCES_LOGS_ARCHIVED}"
     - ssh -i ${HOME}/.ssh/id_rsa -p22 $REMOTE_SERVER_RSYNC_ACCOUNT@$REMOTE_SERVER_IP "mkdir -p $RSYNC_INSTANCES_BIN_PATH/$REMOTE_SERVER_RSYNC_DIR; mkdir -p $RSYNC_INSTANCES_LOGS_PATH; mkdir -p $RSYNC_INSTANCES_LOGS_ARCHIVED; mkdir -p $RSYNC_INSTANCES_DATA_PATH/$REMOTE_SERVER_RSYNC_DIR;"
     - echo "Upload files"
-    - rsync -arzv -e "ssh  -i ${HOME}/.ssh/id_rsa" $RSYNC_INSTANCES_OPTIONS  $CI_PROJECT_DIR/$OPENSILEX_APP_REVISION/* $REMOTE_SERVER_RSYNC_ACCOUNT@$REMOTE_SERVER_IP:$RSYNC_INSTANCES_BIN_PATH/$REMOTE_SERVER_RSYNC_DIR
+    - rsync -arzv -e "ssh -i ${HOME}/.ssh/id_rsa" $RSYNC_INSTANCES_OPTIONS $CI_PROJECT_DIR/artifacts/$OPENSILEX_APP_REVISION/* $REMOTE_SERVER_RSYNC_ACCOUNT@$REMOTE_SERVER_IP:$RSYNC_INSTANCES_BIN_PATH/$REMOTE_SERVER_RSYNC_DIR
     - ls $CI_PROJECT_DIR/opensilex-dev-tools/$CONFIGS_FILES_DIR_PATH
     - echo "scp -i ${HOME}/.ssh/id_rsa -o 'StrictHostKeyChecking no' $CI_PROJECT_DIR/opensilex-dev-tools/$CONFIGS_FILES_DIR_PATH/* ${REMOTE_SERVER_RSYNC_ACCOUNT}@${REMOTE_SERVER_IP}:${RSYNC_INSTANCES_BIN_PATH}/${REMOTE_SERVER_RSYNC_DIR}"
     - scp -i ${HOME}/.ssh/id_rsa -o "StrictHostKeyChecking no" $CI_PROJECT_DIR/opensilex-dev-tools/$CONFIGS_FILES_DIR_PATH/* $REMOTE_SERVER_RSYNC_ACCOUNT@$REMOTE_SERVER_IP:$RSYNC_INSTANCES_BIN_PATH/$REMOTE_SERVER_RSYNC_DIR
@@ -214,14 +217,20 @@ opensilex-release:build:
 
 # Checks that the merge request is valid (target branch must not be master, except if the
 # source is a hotfix branch)
+# The merge request is considered from a hotfix branch if at least one of these conditions is valid :
+# - The branch name starts with "hotfix/"
+# - The merge request has the label "hotfix"
 # Merge requests marked with the Draft: keyword are also blocked
 # No pipeline is triggered for MR from the release branch, because the last release pipeline can be used instead.
 merge-request:check:
   stage: check
   script:
     - if [[ $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" &&
-      ! $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ ^hotfix\/.* ]]; then
+      ! $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ ^hotfix\/.* &&
+      ! $CI_MERGE_REQUEST_LABELS =~ ^(.+,)*hotfix(,.+)*$ ]]; then
     -   echo "Merging from $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME to master is forbidden"
+    -   echo "Only a hotfix can be merged into master"
+    -   echo "To mark this merge request as a hotfix, please add the 'hotfix' label, or rename the branch as hotfix/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
     -   exit 1
     - fi
   rules:
@@ -234,6 +243,9 @@ merge-request:build:
     - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TITLE !~ /^(Draft:|\[Draft\]|\(Draft\)).*/i && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != "release"
   needs:
     - job: "merge-request:check"
+  tags:
+    - stable
+
 
 ####################
 ### TEST DEPLOYMENTS
@@ -271,7 +283,7 @@ trigger:opensilex-develop:deploy:test:
     - apk update
     - apk add git
     - apk add curl
-    - if [[ -z $(git branch --list release) ]]; then
+    - if ! git ls-remote --exit-code --heads origin release; then
     -   echo 'Deploying develop'
     -   curl --request POST --form "variables[DEPLOY]=opensilex-develop" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$CI_COMMIT_SHA" --form "variables[OPENSILEX_APP_REVISION]=$OPENSILEX_APP_REVISION" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
     - else
@@ -308,7 +320,7 @@ opensilex-release:close:
     -   echo 'RELEASE_TAG must be set'
     -   exit 1
     - else
-    -   echo "Finishing release $RELEASE_TAG"
+    -   echo "Closing release $RELEASE_TAG"
     - fi
     # Install packages git & curl
     - apk update
@@ -354,15 +366,81 @@ opensilex-release:close:
     - git push origin $RELEASE_TAG
     # Trigger the merge request to develop
     - >
-      curl -X POST -F "private_token=$JOB_API_TOKEN" -F "source_branch=release" 
-      -F "target_branch=develop" -F "title=[Release] Merge $RELEASE_TAG into develop" 
+      curl -X POST -F "private_token=$JOB_API_TOKEN" -F "source_branch=release"
+      -F "target_branch=develop" -F "title=[Release] Merge $RELEASE_TAG into develop"
       -F "remove_source_branch=true" -F "labels[]=finishing release"
       https://forgemia.inra.fr/api/v4/projects/1675/merge_requests
+    # Transmit release tag variable to next job (name must be different)
+    - echo "PUBLISH_RELEASE_TAG=$RELEASE_TAG" >> opensilex-release:close.env
   rules:
     - if: $CI_COMMIT_BRANCH == "release"
+  artifacts:
+    reports:
+      dotenv:
+        - "opensilex-release:close.env"
   needs:
     - job: "opensilex-release:build"
   when: manual
+
+############################
+## PUBLISH RELEASE TO GITHUB
+############################
+
+opensilex-release:publish:
+  stage: release
+  image: maven:$MVN_VERSION-jdk-$JAVA_VERSION
+  script:
+    - if [[ -z $PUBLISH_RELEASE_TAG ]]; then
+    -   echo 'PUBLISH_RELEASE_TAG must be set'
+    -   exit 1
+    - else
+    -   echo "Publishing release $PUBLISH_RELEASE_TAG"
+    - fi
+    # Install packages curl & jq
+    - apt-get update
+    - apt-get install -y curl
+    - apt-get install -y jq
+    # Remove local tags & fetch them again
+    - git tag -l | xargs git tag -d
+    - git fetch origin --tags
+    # Checkout the release tag & build with the correct revision
+    - git checkout $PUBLISH_RELEASE_TAG
+    - mvn clean install $MAVEN_CLI_OPTS -Drevision=$PUBLISH_RELEASE_TAG -DskipTests=true
+    # Extract release description from changelog
+    # The CHANGELOG.md file should have a section starting with "## [$PUBLISH_RELEASE_TAG]", for example "## [1.0.0-rc+4]"
+    # Otherwise, "Missing release notes" will be set as the release description
+    - echo "Try to extract the release description from changelog..."
+    - RELEASE_DESCRIPTION=$(sed -n  "/^## \[${PUBLISH_RELEASE_TAG}\]/,/^## /p" CHANGELOG.md | head -n -1 | jq -Rsa .)
+    - if [[ "$RELEASE_DESCRIPTION" == '""' ]]; then
+    -   echo "Missing release description for tag $PUBLISH_RELEASE_TAG in the changelog. Please change it later in the Github repository."
+    -   RELEASE_DESCRIPTION="\"# [$PUBLISH_RELEASE_TAG] - $(date --iso-8601)\n\nMissing release notes\n\""
+    - fi
+    # Headers for the queries
+    - AUTHORIZATION="$GITHUB_API_ACCOUNT:$GITHUB_API_TOKEN"
+    - 'ACCEPTS_HEADER="Accept: application/vnd.github+json"'
+    # JSON payload for the creation query
+    # NB : the 'RELEASE_DESCRIPTION' variable already contains the quotes (thanks to jq), that's why they're omitted here
+    - 'CREATE_QUERY_PAYLOAD="{\"tag_name\":\"$PUBLISH_RELEASE_TAG\",\"name\":\"$PUBLISH_RELEASE_TAG\",\"body\":$RELEASE_DESCRIPTION}"'
+    # Create the release
+    - 'echo "\"curl -u \"$AUTHORIZATION\" -X POST -H \"$ACCEPTS_HEADER\" -d \"$CREATE_QUERY_PAYLOAD\" https://api.github.com/repos/OpenSILEX/opensilex/releases"'
+    - CREATE_RESPONSE=$(curl -u "$AUTHORIZATION" -X POST -H "$ACCEPTS_HEADER" -d "$CREATE_QUERY_PAYLOAD" https://api.github.com/repos/OpenSILEX/opensilex/releases)
+    - echo $CREATE_RESPONSE
+    # Asset file
+    - FILENAME=opensilex-release-$PUBLISH_RELEASE_TAG.zip
+    - FILEPATH=opensilex-release/target/$FILENAME
+    # Extract the asset upload URL from the response
+    # The URL is formatted like this : https://uploads.github.com/repos/OpenSILEX/opensilex/releases/73752399/assets{?name,label}
+    # So the last part must be replaced with a valid query parameter (only ?name is required)
+    - UPLOAD_URL=$(echo $CREATE_RESPONSE | jq -r .upload_url | sed -e "s/{.*}/\?name=${FILENAME}/g")
+    # Upload the asset file
+    - 'echo "curl -u \"$AUTHORIZATION\" -X POST -H \"$ACCEPTS_HEADER\" -H "Content-Type: application/zip" -T \"$FILEPATH\" \"$UPLOAD_URL\""'
+    - 'curl -u "$AUTHORIZATION" -X POST -H "$ACCEPTS_HEADER" -H "Content-Type: application/zip" -T "$FILEPATH" "$UPLOAD_URL"'
+  rules:
+    - if: $CI_COMMIT_BRANCH == "release"
+  needs:
+    - job: "opensilex-release:close"
+      artifacts: true
+
 
 # Trigger pipeline for data-analysis module deployment
 #trigger:dataanalysis:deploy:test:
@@ -544,6 +622,8 @@ hamza:build:
   <<: *build_template_with_opensilex
   rules:
     - if: $CI_COMMIT_BRANCH == "hamza"
+  tags:
+    - stable
 
 test:hamza:deploy:
   <<: *deploy_opensilex_before_script
@@ -560,6 +640,8 @@ test:hamza:deploy:
   rules:
     - if: $CI_COMMIT_BRANCH == "hamza"
       when: on_success
+  tags:
+    - stable
   needs:
     - hamza:build
 
@@ -699,31 +781,35 @@ test:bendy:deploy:
     - bendy:build
 
 ###################################
-##  JULIEN-TEST-BUILD-DEPLOYMENT
+##  alexiaChiavarino-TEST-BUILD-DEPLOYMENT
 ###################################
 
-julien:build:
+alexiaChiavarino:build:
   <<: *build_template_with_opensilex
   rules:
-    - if: $CI_COMMIT_BRANCH == "julien"
+    - if: $CI_COMMIT_BRANCH == "alexiaChiavarino"
+  tags:
+    - stable
 
-test:julien:deploy:
+test:alexiaChiavarino:deploy:
   <<: *deploy_opensilex_before_script
   <<: *deploy_opensilex_template
   variables:
-    CONFIGS_FILES_DIR_PATH: "${DEV_TOOLS_REPO_CONF_FILES_PATH}/mistea/julien"
+    CONFIGS_FILES_DIR_PATH: "${DEV_TOOLS_REPO_CONF_FILES_PATH}/mistea/alexiaChiavarino"
     INSTANCE_CONFIGURATION_FILE_NAME: "phis.test.yml"
     OPENSILEX_JAR_ADMIN_PORT: 4087
     OPENSILEX_JAR_PORT: 8087
     REMOTE_SERVER_RSYNC_ACCOUNT: "$REMOTE_PHIS_RSYNC_ACCOUNT"
     REMOTE_SERVER_IP: "$REMOTE_TEST_SERVER_IP"
-    REMOTE_SERVER_RSYNC_DIR: "mistea/julien"
+    REMOTE_SERVER_RSYNC_DIR: "mistea/alexiaChiavarino"
     REMOTE_SERVER_SSH_KEY: "$TEST_SSH_PRIVATE_KEY"
   rules:
-    - if: $CI_COMMIT_BRANCH == "julien"
+    - if: $CI_COMMIT_BRANCH == "alexiaChiavarino"
       when: on_success
+  tags:
+    - stable
   needs:
-    - julien:build
+    - alexiaChiavarino:build
 
 ###################################
 ##  RENAUD-TEST-BUILD-DEPLOYMENT
