Update skos relation model Update Skos relation form

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,49 +1,47 @@
- 
 ########################
-##GLOBAL VARIABLES 
+##GLOBAL VARIABLES
 ########################
 variables:
- ###### COMMON CONFIGS ######
- # GIT CONFIG
- GIT_DEPTH: 5
- GIT_OPTIONS: "--allow-unrelated-histories"
- ## BUILD CONFIGS ##
- # MAVEN CONFIG
- # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
- # when running from the command line.
- MAVEN_CLI_OPTS: "--batch-mode --show-version "
- MAVEN_CACHE_FOLDER: "$CI_PROJECT_DIR/.m2/repository"
- MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
- # DEFAULT SERVER MAVEN VERSION
- MVN_VERSION: 3.6.3
- # DEFAULT SERVER JAVA VERSION
- JAVA_VERSION: 11
- ## DEPLOY CONFIGS ##
- # REMOTE SERVER CONFIG
- RSYNC_INSTANCES_OPTIONS: "--progress --delete"
- RSYNC_INSTANCES_BIN_PATH: "~/opensilex-instances/bin"
- RSYNC_INSTANCES_DATA_PATH: "~/opensilex-instances/data"
- RSYNC_INSTANCES_LOGS_PATH: "~/opensilex-instances/logs"
- RSYNC_INSTANCES_LOGS_ARCHIVED: "~/opensilex-instances/logs/old"
- ###### OPENSILEX ######
- #APP BUILD CONFIG
- OPENSILEX_APP_REVISION: "INSTANCE-SNAPSHOT"
- OPENSILEX_BUILD_PATH: "opensilex-release/target"
- #APP DEPLOY CONFIG
- DEV_TOOLS_REPO_CONF_FILES_PATH: "instances-configuration"
- OPENSILEX_STOP_SERVER_OPTS: "--CONFIG_FILE=$INSTANCE_CONFIGURATION_FILE_NAME"
- OPENSILEX_START_SERVER_OPTS: "--port=$OPENSILEX_JAR_PORT --CONFIG_FILE=$INSTANCE_CONFIGURATION_FILE_NAME --DEBUG -d"
- OPENSILEX_RESET_ONTOLOGIES_OPTS: "sparql reset-ontologies --DEBUG"
+  ###### COMMON CONFIGS ######
+  # GIT CONFIG
+  GIT_DEPTH: 5
+  GIT_OPTIONS: "--allow-unrelated-histories"
+  ## BUILD CONFIGS ##
+  # MAVEN CONFIG
+  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
+  # when running from the command line.
+  MAVEN_CLI_OPTS: "--batch-mode --show-version "
+  MAVEN_CACHE_FOLDER: "$CI_PROJECT_DIR/.m2/repository"
+  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
+  # DEFAULT SERVER MAVEN VERSION
+  MVN_VERSION: 3.6.3
+  # DEFAULT SERVER JAVA VERSION
+  JAVA_VERSION: 11
+  ## DEPLOY CONFIGS ##
+  # REMOTE SERVER CONFIG
+  RSYNC_INSTANCES_OPTIONS: "--progress --delete"
+  RSYNC_INSTANCES_BIN_PATH: "~/opensilex-instances/bin"
+  RSYNC_INSTANCES_DATA_PATH: "~/opensilex-instances/data"
+  RSYNC_INSTANCES_LOGS_PATH: "~/opensilex-instances/logs"
+  RSYNC_INSTANCES_LOGS_ARCHIVED: "~/opensilex-instances/logs/old"
+  ###### OPENSILEX ######
+  #APP BUILD CONFIG
+  OPENSILEX_APP_REVISION: "INSTANCE-SNAPSHOT"
+  OPENSILEX_BUILD_PATH: "opensilex-release/target"
+  #APP DEPLOY CONFIG
+  DEV_TOOLS_REPO_CONF_FILES_PATH: "instances-configuration"
+  OPENSILEX_STOP_SERVER_OPTS: "--CONFIG_FILE=$INSTANCE_CONFIGURATION_FILE_NAME"
+  OPENSILEX_START_SERVER_OPTS: "--port=$OPENSILEX_JAR_PORT --CONFIG_FILE=$INSTANCE_CONFIGURATION_FILE_NAME --DEBUG -d"
+  OPENSILEX_RESET_ONTOLOGIES_OPTS: "sparql reset-ontologies --DEBUG"
 
- # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
- # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
- #CACHE
- YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache_yarn"
- NODE_CACHE: "$CI_PROJECT_DIR/.node"
- EMBDED_MONGO_CACHE: "/root/.embedmongo/"
- # Prevent gitlab clone issues
- GITLAB_HTTPS: "false"
-
+  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
+  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
+  #CACHE
+  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache_yarn"
+  NODE_CACHE: "$CI_PROJECT_DIR/.node"
+  EMBDED_MONGO_CACHE: "/root/.embedmongo/"
+  # Prevent gitlab clone issues
+  GITLAB_HTTPS: "false"
 
 ########################
 ##  CACHE TEMPLATE
@@ -57,9 +55,8 @@ variables:
     paths:
       - $YARN_CACHE_FOLDER
       - $MAVEN_CACHE_FOLDER
-#      - $NODE_CACHE
+      #      - $NODE_CACHE
       - $EMBDED_MONGO_CACHE
-
 
 ########################
 ##  BUILD TEMPLATE
@@ -67,9 +64,9 @@ variables:
 
 .build:instance: &build_template_with_opensilex
   <<: *cache_dependencies
-  before_script: 
-    -  if [ -z "$OPENSILEX_BUILD_PATH" ]; then echo "Missing OPENSILEX_BUILD_PATH variable"; exit 1; fi
-    -  if [ -z "$OPENSILEX_APP_REVISION" ]; then echo "Missing OPENSILEX_APP_REVISION variable"; exit 1; fi
+  before_script:
+    - if [ -z "$OPENSILEX_BUILD_PATH" ]; then echo "Missing OPENSILEX_BUILD_PATH variable"; exit 1; fi
+    - if [ -z "$OPENSILEX_APP_REVISION" ]; then echo "Missing OPENSILEX_APP_REVISION variable"; exit 1; fi
     - |
       if [ ! -z "$COMMIT_SHA_OPENSILEX_DEV" ]; then
         git checkout $COMMIT_SHA_OPENSILEX_DEV
@@ -91,14 +88,14 @@ variables:
 .deploy_opensilex_before_script: &deploy_opensilex_before_script
   before_script:
     # test variables before deployement
-    -  if [ -z "$REMOTE_SERVER_RSYNC_ACCOUNT" ]; then echo "Missing REMOTE_SERVER_RSYNC_ACCOUNT variable"; exit 1; fi
-    -  if [ -z "$REMOTE_SERVER_RSYNC_DIR" ]; then echo "Missing REMOTE_SERVER_RSYNC_DIR variable"; exit 1; fi 
-    -  if [ -z "$REMOTE_SERVER_IP" ]; then echo "Missing REMOTE_SERVER_IP variable"; exit 1; fi
-    -  if [ -z "$CONFIGS_FILES_DIR_PATH" ]; then echo "Missing CONFIGS_FILES_DIR_PATH variable"; exit 1; fi
-    -  if [ -z "$INSTANCE_CONFIGURATION_FILE_NAME" ]; then echo "Missing INSTANCE_CONFIGURATION_FILE_NAME variable"; exit 1; fi
-    -  if [ -z "$REMOTE_SERVER_SSH_KEY" ]; then echo "Missing REMOTE_SERVER_SSH_KEY variable"; exit 1; fi
-    -  if [ -z "$OPENSILEX_JAR_ADMIN_PORT" ]; then echo "Missing OPENSILEX_JAR_ADMIN_PORT variable"; exit 1; fi
-    -  if [ -z "$OPENSILEX_JAR_PORT" ]; then echo "Missing OPENSILEX_JAR_PORT variable"; exit 1; fi
+    - if [ -z "$REMOTE_SERVER_RSYNC_ACCOUNT" ]; then echo "Missing REMOTE_SERVER_RSYNC_ACCOUNT variable"; exit 1; fi
+    - if [ -z "$REMOTE_SERVER_RSYNC_DIR" ]; then echo "Missing REMOTE_SERVER_RSYNC_DIR variable"; exit 1; fi
+    - if [ -z "$REMOTE_SERVER_IP" ]; then echo "Missing REMOTE_SERVER_IP variable"; exit 1; fi
+    - if [ -z "$CONFIGS_FILES_DIR_PATH" ]; then echo "Missing CONFIGS_FILES_DIR_PATH variable"; exit 1; fi
+    - if [ -z "$INSTANCE_CONFIGURATION_FILE_NAME" ]; then echo "Missing INSTANCE_CONFIGURATION_FILE_NAME variable"; exit 1; fi
+    - if [ -z "$REMOTE_SERVER_SSH_KEY" ]; then echo "Missing REMOTE_SERVER_SSH_KEY variable"; exit 1; fi
+    - if [ -z "$OPENSILEX_JAR_ADMIN_PORT" ]; then echo "Missing OPENSILEX_JAR_ADMIN_PORT variable"; exit 1; fi
+    - if [ -z "$OPENSILEX_JAR_PORT" ]; then echo "Missing OPENSILEX_JAR_PORT variable"; exit 1; fi
     ##
     ## Create the SSH directory and give it the right permissions
     ##
@@ -109,7 +106,7 @@ variables:
     ## Install ssh-agent if not already installed, it is required by Docker.
     ## (change apt-get to yum if you use an RPM-based image)
     ##
-    - 'which ssh-agent || ( apt-get update && apt-get install openssh-client -y )'
+    - "which ssh-agent || ( apt-get update && apt-get install openssh-client -y )"
     ##
     ## Run ssh-agent (inside the build environment)
     ##
@@ -165,18 +162,18 @@ variables:
     - ssh -i ${HOME}/.ssh/id_rsa -p22 $REMOTE_SERVER_RSYNC_ACCOUNT@$REMOTE_SERVER_IP "cd ${RSYNC_INSTANCES_BIN_PATH}/${REMOTE_SERVER_RSYNC_DIR}; java -jar ${RSYNC_INSTANCES_BIN_PATH}/${REMOTE_SERVER_RSYNC_DIR}/opensilex.jar server stop --adminPort=$OPENSILEX_JAR_ADMIN_PORT --host=$REMOTE_SERVER_IP ${OPENSILEX_STOP_SERVER_OPTS}"
     - echo "Start with options --adminPort=$OPENSILEX_JAR_ADMIN_PORT --host=$REMOTE_SERVER_IP ${OPENSILEX_START_SERVER_OPTS}"
     - ssh -i ${HOME}/.ssh/id_rsa -p22 $REMOTE_SERVER_RSYNC_ACCOUNT@$REMOTE_SERVER_IP "cd ${RSYNC_INSTANCES_BIN_PATH}/${REMOTE_SERVER_RSYNC_DIR}; java -jar ${RSYNC_INSTANCES_BIN_PATH}/${REMOTE_SERVER_RSYNC_DIR}/opensilex.jar server start --adminPort=$OPENSILEX_JAR_ADMIN_PORT --host=$REMOTE_SERVER_IP ${OPENSILEX_START_SERVER_OPTS}"
-    - AUTOGENERATE_ENVIRONMENT_URL="$REMOTE_SERVER_IP:$OPENSILEX_JAR_PORT"        
-    - echo "Deploy To $AUTOGENERATE_ENVIRONMENT_URL"                 # In script, get the environment URL.
-    - echo "AUTOGENERATE_ENVIRONMENT_URL=$AUTOGENERATE_ENVIRONMENT_URL" >> deploy.env 
+    - AUTOGENERATE_ENVIRONMENT_URL="$REMOTE_SERVER_IP:$OPENSILEX_JAR_PORT"
+    - echo "Deploy To $AUTOGENERATE_ENVIRONMENT_URL" # In script, get the environment URL.
+    - echo "AUTOGENERATE_ENVIRONMENT_URL=$AUTOGENERATE_ENVIRONMENT_URL" >> deploy.env
   environment:
     name: "$CI_COMMIT_REF_NAME-test"
     url: http://$AUTOGENERATE_ENVIRONMENT_URL
   artifacts:
     reports:
-      dotenv: deploy.env        
+      dotenv: deploy.env
 
 # ########################
-# ##  DEFAULT BUILD 
+# ##  DEFAULT BUILD
 # ########################
 
 opensilex:build:
@@ -192,8 +189,8 @@ trigger:sixtine:build:
   script:
     - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$CI_COMMIT_SHA" https://forgemia.inra.fr/api/v4/projects/1757/trigger/pipeline
   rules:
-    - if: $CI_COMMIT_BRANCH == "master"  
-  needs: 
+    - if: $CI_COMMIT_BRANCH == "master"
+  needs:
     - job: "opensilex:build"
 
 # Trigger pipeline for phis module deployment
@@ -203,10 +200,10 @@ trigger:phis:deploy:test:
   script:
     - curl --request POST --form "variables[DEPLOY]=phis-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV"  https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
   rules:
-    - if: $CI_COMMIT_BRANCH == "master" 
-  needs: 
+    - if: $CI_COMMIT_BRANCH == "master"
+  needs:
     - job: "opensilex:build"
-    
+
 # Trigger pipeline for bdg module deployment
 trigger:bdg:deploy:test:
   stage: deploy
@@ -214,10 +211,10 @@ trigger:bdg:deploy:test:
   script:
     - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$CI_COMMIT_SHA" https://forgemia.inra.fr/api/v4/projects/2063/trigger/pipeline
   rules:
-    - if: $CI_COMMIT_BRANCH == "master"  
-  needs: 
+    - if: $CI_COMMIT_BRANCH == "master"
+  needs:
     - job: "opensilex:build"
-    
+
 # Trigger pipeline for data-analysis module deployment
 trigger:dataanalysis:deploy:test:
   stage: deploy
@@ -225,10 +222,9 @@ trigger:dataanalysis:deploy:test:
   script:
     - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$CI_COMMIT_SHA" https://forgemia.inra.fr/api/v4/projects/2076/trigger/pipeline
   rules:
-    - if: $CI_COMMIT_BRANCH == "master"  
-  needs: 
+    - if: $CI_COMMIT_BRANCH == "master"
+  needs:
     - job: "opensilex:build"
-
 
 # Update nightly builds branch
 update:nightly:builds:branch:
@@ -242,7 +238,7 @@ update:nightly:builds:branch:
     - git pull --rebase origin master
     - git push -f origin nightly-builds
   rules:
-    - if: $CI_COMMIT_BRANCH == "master" 
+    - if: $CI_COMMIT_BRANCH == "master"
 
 ########################
 ##  BUILD - TESTS WITH DIFFERENT MAVEN VERSIONS
@@ -251,9 +247,9 @@ update:nightly:builds:branch:
 ##  BUILD TEMPLATE
 .test:build: &test_build_on_schedules
   <<: *cache_dependencies
-  before_script: 
-    -  if [ -z "$JAVA_VERSION" ]; then echo "Missing JAVA_VERSION variable"; exit 1; fi
-    -  if [ -z "$MVN_VERSION" ]; then echo "Missing MVN_VERSION variable"; exit 1; fi
+  before_script:
+    - if [ -z "$JAVA_VERSION" ]; then echo "Missing JAVA_VERSION variable"; exit 1; fi
+    - if [ -z "$MVN_VERSION" ]; then echo "Missing MVN_VERSION variable"; exit 1; fi
     - echo "with_java $JAVA_VERSION and maven $MVN_VERSION with latest version of OpenSILEX/opensilex-dev"
   stage: build
   image: maven:$MVN_VERSION-jdk-$JAVA_VERSION
@@ -262,41 +258,41 @@ update:nightly:builds:branch:
     - ls $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION
     - mv $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION $OPENSILEX_APP_REVISION
   rules:
-    - if: $NIGHTLY_BUILD == "true" 
+    - if: $NIGHTLY_BUILD == "true"
 
 ##  BUILD VERSIONS # example https://gitlab.com/gitlab-org/gitlab-foss/issues/13755
 
 .with_java8: &java8
-  variables: 
+  variables:
     JAVA_VERSION: 8
-  
+
 .with_java11: &java11
-  variables: 
+  variables:
     JAVA_VERSION: 11
- 
+
 .with_java13: &java13
   before_script:
-    - yum install -y git  
-  variables: 
+    - yum install -y git
+  variables:
     JAVA_VERSION: 13
- 
+
 .with_java14: &java14
   before_script:
-    - yum install -y git  
+    - yum install -y git
   variables:
     JAVA_VERSION: 14
 
 test:build:java8:
   <<: *java8
-  <<: *test_build_on_schedules 
-  
+  <<: *test_build_on_schedules
+
 test:build:java11:
   <<: *java11
-  <<: *test_build_on_schedules 
+  <<: *test_build_on_schedules
 
 test:build:java13:
   <<: *java13
-  <<: *test_build_on_schedules 
+  <<: *test_build_on_schedules
 
 test:build:java14:
   <<: *java14
@@ -325,7 +321,7 @@ pages:
 # ##########################################
 # ##  BUILD & DEPLOY FOR MISTEA TEAM
 # ##########################################
- 
+
 ###################################
 ##  ALICE-TEST-SNAPSHOT-DEPLOYMENT
 ###################################
@@ -333,7 +329,7 @@ pages:
 alice:build:
   <<: *build_template_with_opensilex
   rules:
-    - if: $CI_COMMIT_BRANCH == "alice" 
+    - if: $CI_COMMIT_BRANCH == "alice"
 
 test:alice:deploy:
   <<: *deploy_opensilex_before_script
@@ -360,7 +356,7 @@ test:alice:deploy:
 anne:build:
   <<: *build_template_with_opensilex
   rules:
-    - if: $CI_COMMIT_BRANCH == "anne" 
+    - if: $CI_COMMIT_BRANCH == "anne"
 
 test:anne:deploy:
   <<: *deploy_opensilex_before_script
@@ -434,7 +430,6 @@ test:julien:deploy:
   needs:
     - julien:build
 
-
 ###################################
 ##  RENAUD-TEST-BUILD-DEPLOYMENT
 ###################################
@@ -488,7 +483,7 @@ test:vincent:deploy:
       when: on_success
   needs:
     - vincent:build
-    
+
 ###################################
 ##  JEAN-PHILIPPE-TEST-BUILD-DEPLOYMENT
 ###################################
@@ -523,7 +518,7 @@ test:jeanphilippe:deploy:
 emilie:build:
   <<: *build_template_with_opensilex
   rules:
-    - if: $CI_COMMIT_BRANCH == "emilie" 
+    - if: $CI_COMMIT_BRANCH == "emilie"
 
 test:emilie:deploy:
   <<: *deploy_opensilex_before_script
