Refactoring build

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -66,6 +66,8 @@ variables:
 .build:instance: &build_template_with_opensilex
   <<: *cache_dependencies
   before_script: 
+    -  if [ -z "$OPENSILEX_BUILD_PATH" ]; then echo "Missing OPENSILEX_BUILD_PATH variable"; exit 1; fi
+    -  if [ -z "$OPENSILEX_APP_REVISION" ]; then echo "Missing OPENSILEX_APP_REVISION variable"; exit 1; fi
     - |
       if [ ! -z "$COMMIT_SHA_OPENSILEX_DEV" ]; then
         git checkout $COMMIT_SHA_OPENSILEX_DEV
@@ -82,7 +84,13 @@ variables:
   image: maven:$MVN_VERSION-jdk-$JAVA_VERSION
   except:
     - schedules
+  script:
+    - mvn install $MAVEN_CLI_OPTS -Drevision=$OPENSILEX_APP_REVISION
+    - ls $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION
+    - mv $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION $OPENSILEX_APP_REVISION
   artifacts:
+    paths:
+      - $OPENSILEX_APP_REVISION
     expire_in: "3 week"
 
 ########################
@@ -163,26 +171,51 @@ variables:
     name: $CI_JOB_NAME
     url: http://$REMOTE_SERVER_IP:$OPENSILEX_JAR_PORT
 
-# #########
-# Arnaud
-# #########
+
+# ########################
+# ##  DEFAULT BUILD 
+# ########################
+
+opensilex:build:
+  <<: *build_template_with_opensilex
+  only:
+    - master
+
+# Trigger pipeline for sixtine module deployment
+trigger:sixtine:build:
+  stage: deploy
+  image: curlimages/curl
+  script:
+    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$CI_COMMIT_SHA" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/1757/trigger/pipeline
+  only:
+    - master    
+  needs: 
+    - job: "opensilex:build"
+
+# Trigger pipeline for phis module deployment
+trigger:phis:deploy:test:
+  stage: deploy
+  image: curlimages/curl
+  script:
+    - curl --request POST --form "variables[DEPLOY]=phis-test" --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[COMMIT_SHA_OPENSILEX_DEV]=$COMMIT_SHA_OPENSILEX_DEV" --form "variables[COMMIT_SHA_PHIS]=$COMMIT_SHA_PHIS" https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
+  only:
+    - master    
+  needs: 
+    - job: "opensilex:build"
+
+
+# ##########################################
+# ##  BUILD & DEPLOY FOR MISTEA TEAM
+# ##########################################
+ 
+###################################
+##  ARNAUD-TEST-BUILD-DEPLOYMENT
+###################################
 
 arnaud:build:
   <<: *build_template_with_opensilex
-  script: 
-    - mvn install $MAVEN_CLI_OPTS -Drevision=$OPENSILEX_APP_REVISION
-    - ls  $OPENSILEX_BUILD_PATH/
-    - ls  $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION
-    - mv $OPENSILEX_BUILD_PATH/opensilex-release-$OPENSILEX_APP_REVISION $CI_PROJECT_DIR/$OPENSILEX_APP_REVISION
-  artifacts:
-    paths:
-      - $CI_PROJECT_DIR/$OPENSILEX_APP_REVISION
   only:
     - arnaud
-    
-###################################
-##  ARNAUD-TEST-SNAPSHOT-DEPLOYMENT
-###################################
 
 test:arnaud:deploy:
   <<: *deploy_opensilex_before_script
