Small test with integrated opensilex start

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -823,37 +823,37 @@ test:gabriel:front-test:
         - cd opensilex-dev-tools/src/main/resources/docker
         - dockerd &
         - docker compose -p test up &
-        - cd $CI_PROJECT_DIR/artifacts/$OPENSILEX_APP_REVISION
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
-        - echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8081 --adminPort=4081 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
-        - ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8081 --adminPort=4081 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        #- cd $CI_PROJECT_DIR/artifacts/$OPENSILEX_APP_REVISION
+        #- echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        #- ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar system install --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        #- echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        #- ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar sparql reset-ontologies --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        #- echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        #- ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar user add --admin --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
+        #- echo "${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8080 --adminPort=4080 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/"
+        #- ${OPENSILEX_JAVA_EXEC_OPTS} opensilex.jar server start --daemon=true --port=8080 --adminPort=4080 --host=localhost --DEBUG --CONFIG_FILE=/opensilex_mod.yml --BASE_DIRECTORY=/
         - cd $CI_PROJECT_DIR/opensilex-front-tests/e2e
-        - |
-            # Check if OpenSILEX process has started on port 8081 three times, once every 15 seconds
-            for attempt in {1..3}; do
-                sleep 15 # Wait for 15 seconds before the attempt
-                # Check if port 8081 is in use
-                if ss -ltnp | grep ':8081 '; then
-                    echo "Process started on port 8081."
-                    break # Break the loop if port 8081 is in use
-                else
-                    echo "Port 8081 is not in use. Attempt $attempt of 3."
-                fi
-            done
-            
-            # Check if port 8081 was never in use during the attempts
-            if [[ $attempt -eq 3 ]]; then
-                echo "Error: OpenSILEX never started on port 8081 during the allowed 45 seconds." >&2
-                # exit 1
-            fi
-            
-            echo "OpenSILEX has started on port 8080."
-        - sleep 30 # Check port opened in a for or while
+        #- |
+        #    # Check if OpenSILEX process has started on port 8080 three times, once every 15 seconds
+        #    for attempt in {1..3}; do
+        #        sleep 15 # Wait for 15 seconds before the attempt
+        #        # Check if port 8080 is in use
+        #        if ss -ltnp | grep ':8080 '; then
+        #            echo "Process started on port 8080."
+        #            break # Break the loop if port 8080 is in use
+        #        else
+        #            echo "Port 8080 is not in use. Attempt $attempt of 3."
+        #        fi
+        #    done
+        #
+        #    # Check if port 8080 was never in use during the attempts
+        #    if [[ $attempt -eq 3 ]]; then
+        #        echo "Error: OpenSILEX never started on port 8080 during the allowed 45 seconds." >&2
+        #        # exit 1
+        #    fi
+        #
+        #    echo "OpenSILEX has started on port 8080."
+        #- sleep 30 # Check port opened in a for or while
         - npm ci
         - PLAYWRIGHT_HTML_REPORT=$CI_PROJECT_DIR/artifacts/front-tests/playwright-report npx playwright test --output $CI_PROJECT_DIR/artifacts/front-tests/test-results  #  --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL    for sharding
 
